# Generated by Django 3.2.6 on 2021-09-01 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_wizard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wizard',
            options={'managed': False},
        ),
    ]
