# Generated by Django 3.2.6 on 2021-09-01 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_wizard', '0002_alter_wizard_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wizard',
            table='wizard',
        ),
    ]
